### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by maximilianr** [mixu/gr#33] opened 2015-08-29 06:30 UTC
When I run `gr discover` or `. <(gr completion)`, I get this error. I'm on Mac OS X, and have the same error across two computers.

Otherwise gr works excellently (thank you for the superb tool!)

```bash
MacBook-Pro:workspace mr$ gr discover

in ./

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn discover ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by coderjoe** [comment] 2015-09-17 00:49
@maximilianr 

For your problem with aut-discovery give `gr tag discover` a try. This might be a duplicate of #18 

As for `. <(gr completion)` it works fine for me in zsh in Ubuntu, what shell are you using?

**Comment by mixu** [comment] 2015-09-17 05:23
I changed the routing in master to make `gr discover` call `gr tag discover` since this seems to be a be somewhat common issue when getting started with `gr`.

I'd love to see a stack trace for `. <(gr completion)` so feel free to reopen this issue if you can reproduce the issue.

**Closed by mixu** 2015-09-17 05:23 UTC
