### ISSUE TITLE
gr discover failes on Windows

### ISSUE THREAD

**Issue by ddcruver** [mixu/gr#10] opened 2014-11-17 20:44 UTC
Windows 7
Installed Node.JS and NPM installed with Chocolatey by nodejs.install (Which uses the official installer)
Running in Node.js Command Prompt
>gr discover

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by nichtich** [comment] 2015-04-20 12:24
Have you tried `git tag discover`? This issue could be a duplicate of #18

**Comment by mixu** [comment] 2015-09-17 05:24
I changed the routing in master to make `gr discover` call `gr tag discover` since this seems to be a be somewhat common issue when getting started with `gr`.

**Closed by mixu** 2015-09-17 05:24 UTC
